# 5. if Conditional Statements

In this notebook, we will introduce an if conditional statement as another useful tool in its own right and in writing  user-defined functions.  Basically a command is executed only if a specified  condition is true. If not, there is an 'else' option to specify a different command to be executed.

1) Let's start by importing the  numpy library. (Don't forget to press shift+enter to execute each cell.)

In [1]:
import numpy as np

2) Let's create a ist of all numbers between 1 and 10. 

In [2]:
list=np.arange(1,11,1)
list

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3) Let's define a function checksize which takes an input list and outputs whether each number in the list is less than 7. If so, the computer will print "OK" and if not, the computer will print "Too Big!" 

In [3]:
def checksize(list):  #remember the use of :
    for i in list:  #the for statement needs a : at the end. The next line  must also be indented.
        if i<7:     #an if statement also needs a : at the end;  must also indent the next line
            print(i,"is OK")   # computer does this if i<7
        else:      # else needs a : at the end; must indent the next line
            print(i, "is Too Big!") # instruction if x >=7
    return print("Finished!")  #prints a message to the screen when completed

4) Let's see if this works.

In [4]:
checksize(list)

1 is OK
2 is OK
3 is OK
4 is OK
5 is OK
6 is OK
7 is Too Big!
8 is Too Big!
9 is Too Big!
10 is Too Big!
Finished!


<h3> Assignment</h3>

1) Create a new list called list1 consisting of numbers from 1 to 20.  Define a function numberdigits(list1) which goes through the numbers in list1 and prints "is single digit" if the number is single digit and "is double digits" if the number is double digit.  Check that your function runs correctly on list1.

In [5]:
#define list 1 


In [6]:
#definition of the function


In [7]:
#test of the function


2) Define a new list called list2 which has all the even numbers between 0 and 20.  Then define a function halve_upper_half(list2) which outputs half of each number in list2 if the original number is greater than 10.  Check that your function does what it is supposed to do.  

In [8]:
#Define list2
list2=np.arange(0,21,1)
list2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
#Define the function halve_upper_half(list2)
     

In [10]:
#Check that your function does what it's supposed to do


<h4>Solutions</h4>

<h4>Problem 1</h4>

In [11]:
# 1) define list1
list1=np.arange(1,21,1)
list1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
#definition of the function
def numberdigits(input_list):  #remember the use of :
    for i in input_list:  #the for statement needs a : at the end. The next line  must also be indented.
        if i<10:     #an if statement also needs a : at the end;  must also indent the next line
            print(i,"is single digit")   # computer does this if i<7
        else:      # else needs a : at the end; must indent the next line
            if i<100:
                print(i, "is double digit") # instruction if x >=7
    return print("Finished!")  #prints a message to the screen when completed

In [13]:
#test of the function
numberdigits(list1)

1 is single digit
2 is single digit
3 is single digit
4 is single digit
5 is single digit
6 is single digit
7 is single digit
8 is single digit
9 is single digit
10 is double digit
11 is double digit
12 is double digit
13 is double digit
14 is double digit
15 is double digit
16 is double digit
17 is double digit
18 is double digit
19 is double digit
20 is double digit
Finished!


<h4>Problem 2</h4>

In [14]:
#Define list2
list2=np.arange(0,21,1)
list2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [15]:
#Define the function halve_upper_half(list2)
def halve_upper_half(input_list):
    for i in input_list:
        if i>9:
            print("half of ", i," is ",i/2)   

In [16]:
#Check that your function does what it's supposed to do
halve_upper_half(list2)

half of  10  is  5.0
half of  11  is  5.5
half of  12  is  6.0
half of  13  is  6.5
half of  14  is  7.0
half of  15  is  7.5
half of  16  is  8.0
half of  17  is  8.5
half of  18  is  9.0
half of  19  is  9.5
half of  20  is  10.0
