 
## 1.2. Solution Set of  Linear Systems



Linear systems can be represented by equations involving vectors and matrices. These representations enable us to analyze the properties and solution sets of linear systems.

Let $n$ be a positive integer and $\mathbb{R}^n$ be the collection of all ordered $n$-tuples of real numbers. Vectors are denoted by an $n\times 1$ **column matrix** such as  $\vec{u} =\begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n \end{bmatrix}$. A vector whose entries are zero is called **the zero vector** and is denoted by $\vec{0}$.

Two vectors $\vec{u} =\begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n \end{bmatrix}$ and $\vec{v} =\begin{bmatrix} v_1\\ v_2\\ \vdots\\ v_n \end{bmatrix}$ are **equal** if their corresponding entries are equal. That is, if for any $u_i =v_i$ for all $i\leq n$.

Given a vector $\vec{u} =\begin{bmatrix} u_1\\ u_2\\ \vdots\\ u_n \end{bmatrix}$ and a real number $c$, the **scalar product of $\vec{u}$ by $c$** is

$$ c\vec{u} =\begin{bmatrix} cu_1\\ cu_2\\ \vdots\\ cu_n \end{bmatrix}$$

**Algebraic properties of $\mathbb{R}^n$:**

Suppose $\vec{u}$, $\vec{v}$, $\vec{w}$ are in $\mathbb{R}^n$, and $c$ and $d$ are real numbers:

1. $\vec{u}+ \vec{v} = \vec{v}+ \vec{u}$
2. $(\vec{u}+ \vec{v}) + \vec{w} = \vec{u}+ (\vec{v} + \vec{w})$
3. $\vec{u} + \vec{0}= \vec{0} + \vec{u} = \vec{u}$
4. $\vec{u} + (-\vec{u}) = \vec{0}$
5. $c(\vec{u}+ \vec{v}) = c\vec{u}+ c\vec{v}$
6. $(c+d)\vec{u}= c\vec{u}+ d\vec{u}$
7. $c(d\vec{u})= (cv)\vec{u}$

### Vector Equation

A vector $\vec{y} \in \mathbb{R}^n$ is called a **linear combination** of some vectors $\vec{u_1}, \vec{u_2}, \dots, \vec{u_p} \in \mathbb{R}^n$, if there are real numbers $c_1, c_2, \dots, c_p$ such that 

$$ \vec{y} = c_1\vec{u_1} + c_2\vec{u_2} + \dots + c_p\vec{u_p}$$


The **span** of vectors $\vec{u_1}, \vec{u_2}, \dots, \vec{u_p}$, denoted by $\text{Span}( \vec{u_1}, \vec{u_2}, \dots, \vec{u_p})$, is the set of all possible linear combinations:

$$
\text{Span}( \vec{u_1}, \vec{u_2}, \dots, \vec{u_p})= \{c_1\vec{u_1} + c_2\vec{u_2} + \dots + c_p\vec{u_p}: \,\, c_1,c_2, \dots, c_p \in \mathbb{R}\}
$$

In other words, the span represents all the vectors that can be formed by scaling and adding the given vectors $\vec{u_1}, \vec{u_2}, \dots, \vec{u_p}$.

__Example 3:__


Let $\vec{y}=\begin{bmatrix} 7 \\ -4  \\3 \end{bmatrix}$, $\vec{u}= \begin{bmatrix} 2 \\ -3\\-5 \end{bmatrix}$, and $\vec{v} =\begin{bmatrix} 0 \\ 0  \\1 \end{bmatrix}$.

1. Compute $2 \vec{u} - 3 \vec{v}$.
2. Determine if $\vec{y}$ is a linear combination of $\vec{u}$ and $\vec{v}$.

__Solution:__
1. To compute $2 \vec{u} - 3 \vec{v}$, we can perform the following calculations:

$$
2 \vec{u} - 3 \vec{v} = 2 \begin{bmatrix} 2 \\ -3\\-5 \end{bmatrix} - 3 \begin{bmatrix} 0 \\ 0  \\1 \end{bmatrix} = \begin{bmatrix} 4 \\ -6 \\ -10 \end{bmatrix} - \begin{bmatrix} 0 \\ 0  \\3 \end{bmatrix} = \begin{bmatrix} 4 \\ -6 \\ -7 \end{bmatrix}
$$

Thus, $2 \vec{u} - 3 \vec{v} = \begin{bmatrix} 4 \\ -6 \\ -7 \end{bmatrix}$.



In [17]:
import numpy as np

y=np.array([7,-4,3])
print("y=",+ y)

u=np.array([2,-3,-5])
print("u=",+ u)

v=np.array([0,0,1])
print("v=",+ v)

y= [ 7 -4  3]
u= [ 2 -3 -5]
v= [0 0 1]


In [18]:
#1. Compute 2u-3v

2*u+3*v

array([ 4, -6, -7])

2. To determine if $\vec{y}$ is a linear combination of $\vec{u}$ and $\vec{v}$, we need to check if there exist real numbers $c_1$ and $c_2$ such that:

$$
\vec{y} = c_1 \vec{u} + c_2 \vec{v}
$$

Substituting the given values:

$$
\begin{bmatrix} 7  \\ -4  \\ 3 \end{bmatrix} = c_1 \begin{bmatrix} 2 \\ -3 \\ -5 \end{bmatrix} + c_2 \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}
$$

Which is the same as:

$$\begin{bmatrix} 7 \\ -4  \\3 \end{bmatrix}= \begin{bmatrix} 2x_1 + 0\\ -3c_1 + 0\\-5c_1+c_2 \end{bmatrix}$$

or 

\begin{align*}
 2c_1 &= 7 \\
-3c_1 &= -4 \\
-5c_1+ c_2 &= 3 
\end{align*}




We can see that this equation cannot be satisfied because there are no values of $c_1$ and $c_2$ that can make the left-hand side equal to the right-hand side. Therefore, $\vec{y}$ is not a linear combination of $\vec{u}$ and $\vec{v}$.

In conclusion, $\vec{y}$ is not a linear combination of $\vec{u}$ and $\vec{v}$.

### Matrix Equation $A\vec{x}=\vec{b}$

In above example we saw how a vector equation can be traslated into solving a linear system. In general, the vector equation 

$$
x_1\vec{u_1} + x_2\vec{u_1}+ \dots + x_p\vec{u_p} = \vec{y}
$$

has the same solution set as the linear system whose augmented matrix is 

$$
[\vec{u_1}, \vec{u_2}, \dots, \vec{u_p}| \vec{y}]
$$

Note that for brevity, we represent the augmented matrix by its columns.

We can also translate a matrix equation into soling a linear system:

Let A be an $m\times n$ matrix (a rectangular array) with columns $\vec{a_1}, \vec{a_2}, \dots, \vec{a_n}$, and $\vec{x}\in \mathbb{R}^n$. We can define the product of $A$ and $\vec{x}$, denoted by $A\vec{x}$, as the linear combination of the columns of $A$ where the coefficients are the components of $\vec{x}$:


$$A\vec{x}=[\vec{a_1},\  \vec{a_2},\  \dots,\ \vec{a_n}]\, \begin{bmatrix} x_1 \\ x_2\\ \vdots \\ x_n \end{bmatrix}\, := x_1 \vec{a_1} + x_2\vec{a_2} + \dots + x_n \vec{a_n}$$. 


Note that $A\vec{x}$ is defined only if the number of columns of A equals to the numbers entries of $\vec{x}$




__Theorem 2__ (properties of the product of A and $\vec{x}$) Suppose $A$ is an $m\times n$ matrix, $\vec{u}$ and $\vec{v}$ are in $\mathbb{R}^n$ and $c$ is a scalar. Then 

1. $A(\vec{u}+ \vec{v})= A \vec{u} + A \vec{v}$
2. $A(c\vec{u})= c A\vec{u}$


Now let us discuss how to represent a linear system by a matrix equation. Consider:

\begin{align}
   a_{11} x_1 + a_{12} x_2 +& \dots a_{1n} x_n = \,b_1 \\ 
   a_{21} x_1 + a_{22} x_2 +& \dots a_{2n} x_n = \,b_2 \\ 
    &\vdots\\
   a_{m1} x_1 + a_{n2} x_2 +& \dots a_{mn} x_n = \,b_m \\ 
\end{align}

and let   

$$
A= \begin{bmatrix} a_{11} &  a_{12} &\dots & a_{1n}\\ a_{21} &  a_{22} & \dots & a_{2n}\\ \vdots& \vdots& \vdots  \\  a_{m1}& a_{m2} &\dots &  a_{mn}\\
\end{bmatrix}
$$

and $\ \vec{x}= \begin{bmatrix} x_1 \\ x_2\\ \vdots \\ x_n \end{bmatrix}\ $ and  $\ \vec{b}= \begin{bmatrix} b_1 \\ b_2\\ \vdots \\ b_m \end{bmatrix}\ $. The matrix A is called the _coefficient matrix_. Then we can rewrite the above linear system as:


$$A\vec{x}=\vec{b}.$$




__Theorem 3__ Let $A$ be an $m\times n$ matrix. The following statements are logically equivalent:


1. For any $\vec{b}\in \mathbb{R}^m$, the equation $A\vec{x}=\vec{b}$ has a solution.
2. Each $\vec{b}\in \mathbb{R}^m$ is a linear combination of columns of $A$
3. The columns of $A$ span $\mathbb{R}^m$
4. A has a pivot poisition in every row. 



## Solution set of homogenous linear systems

We start with describing the solution set of a simpler linear systems where the right side of equalities are zeros. In matrix form, $A\vec{x}=\vec{0}$; such system is called _homogeneous_. Homogeneous systems are always consistent since $\vec{x}=\vec{0}$ is always a solution. We call $\vec{0}$ the trivial solution of $A\vec{x}=\vec{0}$. 

__Theorem 2:__

The homogenous system $A\vec{x}=\vec{0}$ has a nontrivial solution if and only if it has a non-pivot column. 


Non-pivot columns correspond to free variables; all other variables can be expressed in terms of free variables. 

__Example 4__

Describe the solution set of $10x -4y+ 7z=0$

__Solution__: consider the augmented matrix of the system: $ \begin{bmatrix} 10& -4& 7&& 0\\ \end{bmatrix}$. There is only one pivot columns and y and z are free variables.



$$
\vec{x} = \begin{bmatrix} x \\ y \\z \end{bmatrix} = \begin{bmatrix} 0.4y - 0.7z \\y\\z \end{bmatrix}= \begin{bmatrix} 0.4y \\ y \\0 \end{bmatrix} + \begin{bmatrix} - 0.7z \\ 0 \\ z \end{bmatrix}= 
y \begin{bmatrix} 0.4 \\ 1 \\ 0\end{bmatrix} + z \begin{bmatrix} 0.7 \\0\\1 \end{bmatrix}
$$

Thus, the solution set is span( $\ \begin{bmatrix} 0.4 \\ 1 \\ 0\end{bmatrix},\, \begin{bmatrix} 0.7 \\0\\1 \end{bmatrix}\ $)


__Example 5__

Determine if the following system has a nontrivial solution. Then describe the solution set.


\begin{align*}
3x +5y - 4z &= 0 \\
-3x -2y +4z &= 0 \\
6x + y -8 z &= 0
\end{align*}
 
 
First lets set up the augmented matrix:

In [19]:
A= np.array([[3,5,-4, 0], [-3, -2, 4, 0], [6, 1, -8, 0]])
A

array([[ 3,  5, -4,  0],
       [-3, -2,  4,  0],
       [ 6,  1, -8,  0]])

We transform A into its RREF. Lets recall the elementry operations:

In [20]:
# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row by the sum of itself and a multiple of another 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [21]:
A_1 = replace(A, 1,0, 1)
A_1

array([[ 3.,  5., -4.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 6.,  1., -8.,  0.]])

In [22]:
A_2 = replace(A_1, 2,0, -2)
A_2

array([[ 3.,  5., -4.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 0., -9.,  0.,  0.]])

In [23]:
A_3 = replace(A_2, 2, 1, 3)
A_3

array([[ 3.,  5., -4.,  0.],
       [ 0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

We can see that the third column is a non-pivot column and therefore $z$ is a free variable. Thus, $A\vec{x}=0$ has (infinitely many) one for each choice of $z$. To find the solution set we write back the linear system coresponding to REF of A: 


\begin{align*}
3x +5y - 4z &= 0 \\
3y &= 0 \\
 0&= 0
\end{align*}

Therefore, $x= \frac{-4}{3}z$, and the slution set contains vectors of the foloowing form:


$$
\vec{x} = \begin{bmatrix} x\\y\\z \end{bmatrix} = \begin{bmatrix} \frac{-4}{3}z\\0\\z \end{bmatrix}= z \begin{bmatrix} \frac{-4}{3}\\0\\1 \end{bmatrix}
$$

for $z\in \mathbb{R}$.

In other words, the solution set is $\text{span}\ (\ \begin{bmatrix} \frac{-4}{3}\\0\\1 \end{bmatrix}\ )$



## Solution set of non-homogenoues linear system:

__Theorem 3__ Let $A\vec{x}=\vec{b}$ be a consistent system, and let $\vec{p}$ be a solution. Then the solution set of $A\vec{x}=\vec{b}$ is the set of all vectors of the form $\vec{p}+\vec{h}$ where $\vec{h}$ is any solution to the homogenoues system $A\vec{x}=0$.



__Example 4__ Describe the solution set of $A\vec{x}=\vec{b}$ where 


$A=\begin{bmatrix} 3& 5& -4\\ -3& -2& 4\\ 6& 1& -8 \end{bmatrix}$ and $\vec{b}= \begin{bmatrix} 7\\ -1\\ -4\\  \end{bmatrix}$.

__Solution__ :

In [24]:
# set up the augemented matrix [A|b]
A = np.array([[3,5,-4,7], [-3,-2, 4,-1], [6,1,-8,-4]])

In [25]:
# Row reduce the augmented matrix to reduced echelon form:

A1 = replace(A, 1,0,1)
A1

array([[ 3.,  5., -4.,  7.],
       [ 0.,  3.,  0.,  6.],
       [ 6.,  1., -8., -4.]])

In [26]:
A2 = replace(A1, 2, 0, -2)
A2

array([[  3.,   5.,  -4.,   7.],
       [  0.,   3.,   0.,   6.],
       [  0.,  -9.,   0., -18.]])

In [27]:
A3 = replace(A2, 2, 1, 3)
A3

array([[ 3.,  5., -4.,  7.],
       [ 0.,  3.,  0.,  6.],
       [ 0.,  0.,  0.,  0.]])

In [14]:
A4 = replace(A3, 0, 1, -5/3)
A4

array([[ 3.,  0., -4., -3.],
       [ 0.,  3.,  0.,  6.],
       [ 0.,  0.,  0.,  0.]])

In [15]:
A5 = scale(A4, 0, 1/3)
A5

array([[ 1.        ,  0.        , -1.33333333, -1.        ],
       [ 0.        ,  3.        ,  0.        ,  6.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [16]:
A6 = scale(A5, 1, 1/3)
A6

array([[ 1.        ,  0.        , -1.33333333, -1.        ],
       [ 0.        ,  1.        ,  0.        ,  2.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

Now we can express each dependent variable in terms of free variables:

We have $x_1 - \frac{4}{3} x_3 = -1$, $x_2= 2$, and $x_3$ is free. As a vector, the general solution of $A\vec{x}=\vec{b}$ is 

$$\begin{bmatrix} x_1 \\ x_2 \\ x_3 \\ \end{bmatrix} = \begin{bmatrix} -1 + \frac{4}{3} x_3\\ 2\\ x_3\end{bmatrix} = \begin{bmatrix} -1 \\ 2 \\ 0 \end{bmatrix} + x_3 \begin{bmatrix} \frac{4}{3} \\ 0 \\ 1 \end{bmatrix}$$



## Linear Independency:

The homogeneous system defined above can be described as vector equations.


An index set of vectors $\{\vec{v_1}, \vec{v_2}, \dots \vec{v_p}\}$ in $\mathbb{R}^n$ is called a _linearly independet set_ if the vector equation:

$$ x_1 \vec{v_1} + x_2 \vec{v_2} + \dots + x_p \vec{v_p} = 0$$

has only the trivial solution. The set is called _linearly dependent_ if there are real numbers $c_1,c_2, \dots c_p$, not all zero,such that 

$$ c_1 \vec{v_1} + c_2 \vec{v_2} + \dots + c_p \vec{v_p} = 0$$


Note that linear independence equation is equivalent to a homogenous system $A\vec{x}$ where $A$ is a matrix whose columns are $\vec{v_i}s$. Thus, 

the columns of the matrix A are linearly independent if and only if $A\vec{x}=0$ has only trivial solution.



__Lemma 1__
A set of vectors containing zero vector is linearly dependent.

__proof:__ Consider the linear independece equation for such sets $x_1 \vec{0} + x_2 \vec{v_1} + \dots + x_p \vec{v_p} = 0$. By choosing a non-zero $x_1$, we can form a nontrivial solution for 



__Lemma 2__
A set of two vectors is linearly dependent if and only if one is a multiple of the other. 

__Proof__: if one of them is zero, by __Lemma 1__ the set is linearly dependent. Assume they are not zero. If $x_1 \vec{u} + x_2 \vec{v}= 0$ has nontrivial solutions, at least one of $x_1$, $x_2$ is not 
zero. Without losing of generality, assume $x_2$ is not zero. Then we have $\vec{v} = \frac{x_1}{x_2} \vec{u}$.



__Example 5:__ 

Determine if the following set of vectors are linearly independent:

1. $\vec{u} = \begin{bmatrix} 1\\2\\3 \end{bmatrix} \,\,  \vec{v} = \begin{bmatrix} 4\\5\\6 \end{bmatrix}, \,\,  \vec{w} = \begin{bmatrix} 7\\8\\9 \end{bmatrix}$

__Solution__
Lets set up the matrix equation:





__Exercises:__

1. Find a $3 \times 3$ matrix $A$ and vectors $\vec{b}, \vec{c} \in \mathbb{R}^3$ such that $A\vec{x}=\vec{b}$ has a solution and $A\vec{x}=\vec{c}$ does not.

2. Given the system of equations:
\begin{align*}
3x + 2y &= 1 \\
x - 2y + z &= 5 \\
2x - z &= 0
\end{align*}

Write this system as:
   1. a vector equation
   2. a matrix equation.
   3. True or False? $\vec{0} \in \text{span} \{\vec{v}_1, \vec{v}_2, \vec{v}_3\}$.
   4. True or False? $\vec{v}_1 \in \text{span} \{\vec{v}_1, \vec{v}_2, \vec{v}_3\}$.
   5. True or False? $\text{span} \{\vec{v}_1, \vec{v}_2\} \subseteq \text{span} \{\vec{v}_1, \vec{v}_2, \vec{v}_3\}$.
   
   
   
   
   
   
   
2. Describe and compare the solution set of 




  (a) $A\vec{x}= \vec{0}$
  
  
  (b) $A\vec{x}= \vec{b}$

where 
$$
 A= \begin{bmatrix}-3 & -7  & 9\\ 1 & 3  & -5\\ \frac{1}{2} & 2 &-4\\  \end{bmatrix} \quad \text{and} \quad 
 b= \begin{bmatrix} 8\\ 7 \\ -12 \\  \end{bmatrix}
$$   


3.  Is $\left\lbrace\ \  \begin{bmatrix} 1 \\ 2  \\3 \end{bmatrix},  
\begin{bmatrix} 4 \\ 5  \\6 \end{bmatrix}, \begin{bmatrix} 7 \\ 8 \\9 \end{bmatrix}\ \ \right\rbrace$ linearly independent or dependent?




4. Explain why a set 4 vectors must be linearly DEPENDENT in $\mathbb{R}^3$.
