# 2. Matrix Algebra

This section focuses on matrix algebra and its properties. We will explore how operations involving matrices are connected to linear systems of equations.

Consider matrix $A$, which is an $m \times n$ matrix with $m$ rows and $n$ columns:

$$
A = \begin{bmatrix} a_{11} &  a_{12} &\dots & a_{1n}\\ a_{21} &  a_{22} & \dots & a_{2n}\\ \vdots& \vdots& \vdots  \\  a_{m1}& a_{m2} &\dots &  a_{mn}\\
\end{bmatrix}
$$

The entry in the $i$th row and $j$th column is referred to as the __$(i,j)$-entry__ of matrix $A$. Entries with the same row and column index ($a_{i,i}$ for any $i$) are called __diagonal entries__ of $A$. The $i$th column of $A$, denoted as $a_i$, represents a vector in $\mathbb{R}^m$. We can represent matrix $A$ in a compact form by its columns:

$$
A= \begin{bmatrix} a_{1} &  a_{2} &\dots & a_{n}\\ \end{bmatrix},
$$

or by its entries:

$$A= (a_{i,j})$$

A matrix whose entries are all zero is called a _zero matrix_, denoted by $0$. The size of a zero matrix is usually clear from the context. 

Now, let's consider an $n \times n$ matrix $A$. We have the following definitions:

1. _Identity matrix_, denoted by $I_n$, contains 1 on the diagonal and 0 everywhere else. 
2. _Diagonal matrix_ has all nondiagonal entries equal to zero. Identity matrices are diagonal.
3. _Upper triangular matrix_ has all entries below the diagonal equal to zero.
4. _Lower triangular matrix_ has all entries above the diagonal equal to zero.
5. _Triangular matrix_ if it is either upper triangular or lower triangular.

__Example 1__

As we have seen before, we use NumPy arrays to represent matrices:

In [1]:
import numpy as np

A = np.array([[0, 2, -1],[2, 3, 1]])
print('A=', A)


#Size of A

print('A has ', A.shape[0],  'rows, and', A.shape[1],  'columns')

print(30*'*')

B = np.array([[1, 2, 3],[4, 5, 6]])
print('A=', B)


#Size of B

print('B has ', B.shape[0],  'rows, and', B.shape[1],  'columns')


print(30*'*')

C = np.array([[0, 2] ,[2, 3],[5, -2]])
print('C=', A)


#Size of A

print('C has ', C.shape[0],  'rows, and', C.shape[1],  'columns')




A= [[ 0  2 -1]
 [ 2  3  1]]
A has  2 rows, and 3 columns
******************************
A= [[1 2 3]
 [4 5 6]]
B has  2 rows, and 3 columns
******************************
C= [[ 0  2 -1]
 [ 2  3  1]]
C has  3 rows, and 2 columns


## 2.1 Algebraic operations on matrices

The arithmetic operations defined for vectors can be extended to matrices:

1. Two matrices $A$ and $B$ are equal if they have the same size and entries.

2. The sum of two matrices is defined for matrices of the same size: Let $A = (a_{ij})$ and $B = (b_{ij})$ be two $m \times n$ matrices. Then $A+B$ is an $m \times n$ matrix whose entries are the sums of the corresponding entries of $A$ and $B$:

$$ A+B = (a_{ij} + b_{ij}).$$

3. The scalar product $cA$ for a scalar $c \in \mathbb{R}$ and a matrix $A$ is a matrix of the same size as $A$ whose entries are $c$ times the entries of $A$:

$$ cA = (ca_{ij}) $$

__Theorem 1__ (Properties of sum and scalar product)

Let $A$, $B$, and $C$ have the same size, and let $c$ and $d$ be real numbers.

1. $A+B = B+A$
2. $(A+B)+C = A+(B+C)$
3. $A+ 0 = A$
4. $c(A+B) =  cA + cB$
5. $(c+d)A = cA + dA$
6. $c(dA)=(cd)A$

__Example 2:__ 
Consider the matrices in Example 1. Compute the following:

1. $3A-B$

2. $A+C$

In [2]:
#1.
3*A-B

array([[-1,  4, -6],
       [ 2,  4, -3]])

$A+C$ is not defined because $A$ and $C$ are not of the same size.

In [3]:
#2.
A+C

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

#### Matrix Product:

Let $A$ be an $m \times n$ and $B$ be an $n \times p$ matrix. The product AB is an $m\times p$ matrix whose columns are $Ab_1, Ab_2, \dots, Ab_p$:

$$
AB= \begin{bmatrix} Ab_{1} &  Ab_{2} &\dots & Ab_{n}\\ \end{bmatrix}.
$$

We can also descibe the matrix product by the entries: the (ij)-entry of $AB$ is the product of the ith-row of A and the jth column of B in the following way:

$$
a_ib_j = \begin{bmatrix} a_{i1} &  a_{i2} &\dots & a_{in}\\ \end{bmatrix} \begin{bmatrix} b_{1j} &  b_{2j} &\dots & a_{nj}\\ \end{bmatrix} = a_{i1}b_{j1} + a_{i2}b_{2j} + \dots + a_{in}b_{nj} = \Sigma^{n}_{k=1}a_{ik}b_{kj}
$$


The product $BA$ is not defined if $p\neq m$ (the _neighboring dimensions_
do not match).


__Example 3__

Let $A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$ and $B = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6\\ \end{bmatrix}$. Compute $AB$ and BA.

__Solution:__ $A$ is a $2 \times 3$ and B is a $3 \times 2$ matrix. We expect AB to be a $2\times 2$  matrix: 




In [4]:
import numpy as np

#Set up A
A = np.array([[1,2,3],[4,5,6]])

#Set up B
B = np.array([[1,2],[3,4],[5,6]])

#Compute the product with numpy.dot()
AB= np.dot(A,B)

print(AB)

[[22 28]
 [49 64]]


Now lets compute $BA$:

In [5]:
#Compute the product BA
BA= np.dot(B,A)

print(BA)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


__Example 4__ 

Let $C = \begin{bmatrix} 1 & 2 & 3 & 4 \\ 4 & 5 & 6 & 7 \end{bmatrix}$. The matrix product $AC$ is not defined because the number of columns in matrix $A$ does not match the number of rows in matrix $C$. If we proceed with computing $AC$ we will get: 

In [7]:
C = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

# Compute AC
AC = np.dot(A, C)

print(AC)


ValueError: shapes (2,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

__Theorem 2 (Properties of matrix product):__

Let $A$ be an $m\times n$ matrix, and let $B$ and $C$ be matrices of the same size for which the following sum and product operations are defined:

1. $A(BC) = (AB)C$
2. $A(B+C) = AB + AC$
3. $(B+C)A = BA + CA$
4. $r(AB) = (rA)B = A(rB)$ for any scalar $r\in \mathbb{R}$.
5. $I_mA = AI_n = A$

### Transpose and Inverse:

Given an $m\times n$ matrix $A$, the transpose of $A$ is the $n\times m$ matrix denoted by $A^T$, whose columns are the corresponding rows of $A$.

__Example 5:__

If $M = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}$, then $M^T = \begin{bmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{bmatrix}$.


In [10]:
M = np.array([[1,2],[3, 4],[5,6]])

#Compute the the transpose of M
M_T = M.transpose()

print("M =", '\n', M, '\n\n', "M_T =",'\n', M_T)

M = 
 [[1 2]
 [3 4]
 [5 6]] 

 M_T = 
 [[1 3 5]
 [2 4 6]]


### Inverse of a square matrix

An $n\times n$ matrix $A$ is called invertible if there exists an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, $B$ is referred to as the inverse of $A$, denoted as $A^{-1}$. It is important to note that not all matrices are invertible and are sometimes referred to as singular.

__Theorem 3:__

Let $A= \begin{bmatrix} a & b \\ c & d\\ \end{bmatrix}$. If $ad-bc \neq 0$, then $A$ is invertible, and its inverse is given by:

$$
A^{-1}= \frac{1}{ad-bc}\begin{bmatrix} d & -b \\ -c & a\\ \end{bmatrix}
$$

$ad-bc$ is called the determinant of matrix A. The determinant plays a crucial role in determining the invertibility of a square matrix. If the determinant is zero, i.e., $ad-bc = 0$, then matrix A is not invertible. Determinants of matrices will be discussed in the next section, where we will explore their properties and computation methods.

__Example 6:__

1. Find the inverse of $M= \begin{bmatrix} 1 & 2 \\ 3 & 4\\ \end{bmatrix}$.
2. Find the inverse of $N= \begin{bmatrix} 1 & 2 \\ 2 & 4\\ \end{bmatrix}$.

Solution:

To find the inverse of a $2\times 2$ matrix, we can write a Python code that performs the computation.

In [15]:
M = np.array([[1, 2], [3, 4]])
N = np.array([[1, 2], [2, 4]])

# Compute the inverse
def inverse_matrix(matrix):
    a, b = matrix[0]
    c, d = matrix[1]
    
    det = a * d - b * c

    if det == 0:
        print(matrix, "is not invertible")
    else:
        D = 1 / det    
        inverse = np.zeros((2, 2))
        inverse[0, 0] = D * d
        inverse[0, 1] = -D * b
        inverse[1, 0] = -D * c
        inverse[1, 1] = D * a

        print(inverse)

In [16]:
inverse_matrix(M)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
inverse_matrix(N)

[[1 2]
 [2 4]] is not invertible


__Theorem 3__ (Properties of the inverse matrix)

Let $A$ and $B$ be two invertible $n\times n$ matrices.

1. $(A^{-1})^{-1} = A$
2. $(AB)^{-1} = B^{-1}A^{-1}$
3. $(A^{T})^{-1} = (A^{-1})^{T}$


### Computing the inverse of a matrix

__Theorem 4__

An $n\times n$ matrix $A$ is invertible if and only if it is row equivalent to the identity matrix $I_n$. 


We can use this theorem to find the inverse of a matrix using the row reduction method: set up the augmented matrix $[A|I_n]$ and perform row operations until the left side of the augmented matrix becomes the identity matrix $I_n$. If this is achieved, then the right side of the augmented matrix will be the inverse of $A$. Otherwise, if the left side does not become $I_n$, then the matrix $A$ is not invertible.


__Example 7__ 

Find the inverse of $M= \begin{bmatrix} 0 & 1 & 2\\ 1 & 0 & 3\\ 4 & -3 & 8 \end{bmatrix}$.

__Solution__ Lets set up the augmented matrix and find its RREF:


$$[M|I_3]= \begin{bmatrix} 0 & 1 & 2 && 1 & 0 & 0\\ 1 & 0 & 3 &&  0 & 0 & 1 \\ 4 & -3 & 8 && 0 & 0 & 1\end{bmatrix}$$

In [18]:
A = np.array([[0,1,2, 1,0,0], [1,0,3, 0, 1, 0], [4, -3, 8, 0, 0, 1]])
A

array([[ 0,  1,  2,  1,  0,  0],
       [ 1,  0,  3,  0,  1,  0],
       [ 4, -3,  8,  0,  0,  1]])

In [21]:
# Elementry row operations:

# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row by the sum of itself and a multiple of another 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [22]:
A_1 = swap(A, 0, 1)
A_1

array([[ 1.,  0.,  3.,  0.,  1.,  0.],
       [ 0.,  1.,  2.,  1.,  0.,  0.],
       [ 4., -3.,  8.,  0.,  0.,  1.]])

In [23]:
A_2 = replace(A_1, 2, 0, -4)
A_2

array([[ 1.,  0.,  3.,  0.,  1.,  0.],
       [ 0.,  1.,  2.,  1.,  0.,  0.],
       [ 0., -3., -4.,  0., -4.,  1.]])

In [24]:
A_3 = replace(A_2, 2, 1, 3)
A_3

array([[ 1.,  0.,  3.,  0.,  1.,  0.],
       [ 0.,  1.,  2.,  1.,  0.,  0.],
       [ 0.,  0.,  2.,  3., -4.,  1.]])

In [25]:
A_4 = scale(A_3, 2, 1/2)
A_4

array([[ 1. ,  0. ,  3. ,  0. ,  1. ,  0. ],
       [ 0. ,  1. ,  2. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  1.5, -2. ,  0.5]])

In [26]:
A_5 = replace(A_4, 1, 2, -2)
A_5

array([[ 1. ,  0. ,  3. ,  0. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  1. ,  1.5, -2. ,  0.5]])

In [27]:
A_6 = replace(A_5, 0, 2, -3)
A_6

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  1. ,  1.5, -2. ,  0.5]])

We can see that the resulting matrix is in the form $[I_3, B]$. Thus, $B= \begin{bmatrix} -4.5 & 7 & -1.5\\ -2 &  4 & -1 \\ 1.5 & -2 & 0.5 \\ \end{bmatrix}$ is the inverse of $M$.

__Theorem 4__ (The Invertible Matrix Theorem)

Let $A$ be an $n\times n$ matrix. The following statements are equivalent:

1. $A$ is an invertible matrix.
2. $A$ is row equivalent to $I_n$.
3. The equation $A\vec{x}=0$ has only the trivial solution ($\vec{x} = \mathbf{0}$).
4. The columns of $A$ form a linearly independent set.
5. The equation $A\vec{x}=\vec{b}$ has a unique solution ($\vec{x} = A^{-1}\vec{b}$).
6. The columns of $A$ span $\mathbb{R}^n$.

__Example 8__

Find the solution set of the following linear systems:

1. $M\vec{x}=0$, where $M$ is the matrix from Example 7.

__Solution:__ Since $M$ is invertible, by the Invertible Matrix Theorem (IMT) part (3), the only solution to $M\vec{x}=0$ is the zero vector $\vec{x}=\mathbf{0}$.

2. $M\vec{x}=\vec{b}$, where $M$ is the matrix from Example 7 and $\vec{b}=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$.

__Solution:__ By IMT part (5), the only solution to $M\vec{x}=\vec{b}$ is $\vec{x}=M^{-1}\vec{b}$. In Example 7, we computed the inverse of $M$:

$A^{-1} = \begin{bmatrix} -4.5 & 7 & -1.5 \\ -2 & 4 & -1 \\ 1.5 & -2 & 0.5 \end{bmatrix}$

In the following cell, we use $B$ to represent $A^-1$ in order to simplify notation:

In [29]:
B= np.array([[-4.5, 7, -1.5], [-2, 4, -1], [1.5, -2, 0.5]])

b = np.array ([[1], [2], [3]])

#compute Bb

x = np.dot(B,b)
x

array([[ 5.],
       [ 3.],
       [-1.]])

Lets check our solution: 

In [30]:
M = np.array([[0,1,2], [1,0,3], [4,-3,8]])

#compute Mx

Mx= np.dot(M,x) 
Mx

array([[1.],
       [2.],
       [3.]])

which is equal to $\vec{b}$!

__Exercises:__

1. Which pair of the following matrices can be multiplied? Compute their matrix product.

$A = \begin{bmatrix}
1 & 3 \\
4 & -2 \\
3 & 2
\end{bmatrix}$

$B = \begin{bmatrix}
1 & 4 & 5\\
0 & 2  & 3
\end{bmatrix}$ 


$C = \begin{bmatrix}
1 & 3 & 0\\
2 & -1  & 3 \\
0 & 1 & 1
\end{bmatrix}$ 


2. Find two matrices $A$ and $B$ such that the products $AB$ and $BA$ are defined but $AB \neq BA$.


3.  Given $A= \begin{bmatrix}
1 & 2 \\ 1& 2
\end{bmatrix}$, find a nonzero matrix  $C$ for which $AC= \begin{bmatrix}
0 & 0 \\ 0 & 0
\end{bmatrix}$.


4. Suppose $A= \begin{bmatrix}
1 & 2 \\
0 & -1 \\
3 & 0
\end{bmatrix}$

    (a) Compute $A^T$.
    
    (b) Is $AA^T$ invertible? 
    
    (c) Is $A^TA$ invertible?