# 2. Matrices

## 2.1 Matrix Algebra

This section focuses on matrix algebra and its properties. We will also explore how operations involving matrices are connected to linear systems.

## Matrices

Consider matrix $A$, which is an $m \times n$ matrix with $m$ rows and $n$ columns:

$$
A = \begin{bmatrix} a_{11} &  a_{12} &\dots & a_{1n}\\ a_{21} &  a_{22} & \dots & a_{2n}\\ \vdots& \vdots& \vdots  \\  a_{m1}& a_{m2} &\dots &  a_{mn}\\
\end{bmatrix}
$$

The entry in the $i$th row and $j$th column is referred to as the __$(i,j)$-entry__ of matrix $A$. Entries with the same row and column index ($a_{i,i}$ for any $i$) are called __diagonal entries__ of $A$. The $i$th column of $A$, denoted as $a_i$, represents a vector in $\mathbb{R}^m$. We can represent matrix $A$ in a compact form by its columns:

$$
A= \begin{bmatrix} a_{1} &  a_{2} &\dots & a_{n}\\ \end{bmatrix},
$$

or by its entries:

$$A= (a_{i,j})$$

A matrix whose entries are all zero is called a __zero matrix__, denoted by $0$. The size of a zero matrix is usually clear from the context. 

An $n \times n$ matrix is called: 

1. the __identity matrix__, denoted by $I_n$, if it has 1 on the diagonal and 0 everywhere else. 
2.  a __diagonal matrix__ if it has all nondiagonal entries equal to zero. Identity matrices are diagonal.
3. an __upper triangular matrix__ if it has all entries below the diagonal equal to zero.
4. a _lower triangular matrix_ if it has all entries above the diagonal equal to zero.
5.  a_triangular matrix_ if it is either upper triangular or lower triangular.

__Example 1__

Let $A = \begin{bmatrix} 0 & 2 & -1\\ 2 & 3 & 1 \end{bmatrix}$. 

As we have seen before, we use NumPy arrays to represent A. Note that each list in the array represent a row of A.

In [1]:
import numpy as np

A = np.array([[0, 2, -1],[2, 3, 1]])
print('A =\n', A)


A =
 [[ 0  2 -1]
 [ 2  3  1]]


$A$ is a $2 \times 3$ matrix. The following cell shows how to find the size of $A$:

In [2]:
#Size of A

print('A has ', A.shape[0],  'rows, and', A.shape[1],  'columns')

A has  2 rows, and 3 columns


We can also print rows and columns of $A$:

In [12]:
print('The first row of A is ', A[0,:])

print(30*'*')

print('\n The second row of A is ', A[1,:])

print(30*'*')

print('\n The first column of A is ', A[:,0])

print(30*'*')

print('\n The second column of A is ', A[:,1])

print(30*'*')

print('\n The third column of A is ', A[:,2])



The first row of A is  [ 0  2 -1]
******************************

 The second row of A is  [2 3 1]
******************************

 The first column of A is  [0 2]
******************************

 The second column of A is  [2 3]
******************************

 The third column of A is  [-1  1]


The following cell shows how to generate an identity matrix of an arbitary size:

In [3]:
# 3x3 identity matrix
I_3 = np.eye(3)

print('I_3 = \n \n', I_3)

# 4x4 identity matrix I_4
I_4 = np.eye(4)

print('\n I_4 = \n \n', I_4)

# 5x5 identity matrix I_5
I_5 = np.eye(5)

print('\n I_5 = \n \n', I_5)

I_3 = 
 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 I_4 = 
 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 I_5 = 
 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Let's have more examples:

In [4]:
B = np.array([[1, 2, 3],[4, 5, 6]])
print('B =\n', B)


#Size of B

print('\n B has ', B.shape[0],  'rows, and', B.shape[1],  'columns')

# the second column of B

print('\n The second column of B is ', B[:,1])

print(30*'*')

C = np.array([[0, 2] ,[2, 3],[5, -2]])
print('\n C = \n', C)


#Size of C

print('\n C has ', C.shape[0],  'rows, and', C.shape[1],  'columns')


# print the columns of C

for i in range(C.shape[1]):
    print('\n The', i+1, '-th column of C is ', B[:,i])



B =
 [[1 2 3]
 [4 5 6]]

 B has  2 rows, and 3 columns

 The second column of B is  [2 5]
******************************

 C = 
 [[ 0  2]
 [ 2  3]
 [ 5 -2]]

 C has  3 rows, and 2 columns

 The 1 -th column of C is  [1 4]

 The 2 -th column of C is  [2 5]


## Basic Algebraic Operations

The arithmetic operations defined for vectors can be extended to matrices:

1. Two matrices $A$ and $B$ are equal if they have the same size and entries.



2. The __sum__ of matrices is defined for matrices of the same size: 

let $A = (a_{ij})$ and $B = (b_{ij})$ be two $m \times n$ matrices. Then $A+B$ is an $m \times n$ matrix whose entries are the sums of the corresponding entries of $A$ and $B$:

$$ A+B = (a_{ij} + b_{ij}).$$



3. The __scalar product__ $cA$ for a scalar $c \in \mathbb{R}$ and a matrix $A$ is a matrix of the same size as $A$ whose entries are $c$ times the entries of $A$:

$$ cA = (ca_{ij}) $$

__Theorem 1__ (properties of sum and scalar product)

Let $A$, $B$, and $C$ have the same size, and let $c$ and $d$ be real numbers.

1. $A+B = B+A$
2. $(A+B)+C = A+(B+C)$
3. $A+ 0 = A$
4. $c(A+B) =  cA + cB$
5. $(c+d)A = cA + dA$
6. $c(dA)=(cd)A$

__Example 2:__ 

Consider the matrices in Example 1. Compute the following:

1. $3A-B$

2. $A+C$

__Solution:__

In [127]:
#1

3*A-B

array([[-1,  4, -6],
       [ 2,  4, -3]])

$A+C$ is not defined because $A$ and $C$ are not of the same size:

In [128]:
#2.
A + C

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

## Matrix Product


Let $A$ be an $m \times n$ and $B$ be an $n \times p$ matrix. The product AB is an $m\times p$ matrix whose columns are $Ab_1, Ab_2, \dots, Ab_p$:

$$
AB= \begin{bmatrix} Ab_{1} &  Ab_{2} &\dots & Ab_{n}\\ \end{bmatrix}.
$$

We can also descibe the matrix product by the entries: the ($ij$)-entry of $AB$ is the product of the $i$th-row of $A$ and the $j$th column of $B$ in the following way:

$$
a_ib_j = \begin{bmatrix} a_{i1} &  a_{i2} &\dots & a_{in}\\ \end{bmatrix} \begin{bmatrix} b_{1j} &  b_{2j} &\dots & a_{nj}\\ \end{bmatrix} = a_{i1}b_{j1} + a_{i2}b_{2j} + \dots + a_{in}b_{nj} = \Sigma^{n}_{k=1}a_{ik}b_{kj}
$$


The product $BA$ is not defined if $p\neq m$ (the _neighboring dimensions_
do not match).


__Example 3__

Let $A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$ and $B = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6\\ \end{bmatrix}$. Compute $AB$ and $BA$.

__Solution:__ 

$A$ is a $2 \times 3$ and B is a $3 \times 2$ matrix; so the product is defined. In Python we use the sympol `@` to compute the matrix product

In [5]:
import numpy as np

#A
A = np.array([[1,2,3],[4,5,6]])

#B
B = np.array([[1,2],[3,4],[5,6]])

#Compute the matrix product
AB = A @ B

print(AB)

[[22 28]
 [49 64]]


Now let's compute $BA$:

In [6]:
#Compute the product BA
BA = B @ A

print(BA)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


__Example 4__ 

Let $C = \begin{bmatrix} 1 & 2 & 3 & 4 \\ 4 & 5 & 6 & 7 \end{bmatrix}$. The matrix product $AC$ is not defined because the number of columns in matrix $A$ does not match the number of rows in matrix $C$. If we proceed with computing $AC$ we will get: 

In [7]:
C = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

# Compute AC
AC = A @ C

print(AC)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

__Power of Square Matrices__

We can raise a square matrix $A$ to the power of a natural number using matrix multiplication. The matrix power is a fundamental idea in several linear algebra applications such as the long-term behavior of disceret dynamical systems. 

__Example 5:__

Let $M = BA$ where $A$ and $B$ are matrices in Example 3. Compute $M^{4}$.

In [132]:
#C
M = BA
#Compute C^4
M4 = M @ M @ M @ M

print('C^4 =\n ', M4 )

C^4 =
  [[ 5447976  7470048  9492120]
 [11879096 16288144 20697192]
 [18310216 25106240 31902264]]


Interestingly, computing the power of diagonal matrices is relatively straightforward.

__Example 6:__

Let's consider the matrix $A = \begin{bmatrix} 2 & 0\\ 0 & 5 \end{bmatrix}$. We can observe the pattern for computing powers of $A$:

- $A^2 = \begin{bmatrix} 2^2 & 0\\ 0 & 5^2 \end{bmatrix} = \begin{bmatrix} 4 & 0\\ 0 & 25 \end{bmatrix}$

- $A^3 = \begin{bmatrix} 2^3 & 0\\ 0 & 5^3 \end{bmatrix} = \begin{bmatrix} 8 & 0\\ 0 & 125 \end{bmatrix}$

- $A^4 = \begin{bmatrix} 2^4 & 0\\ 0 & 5^4 \end{bmatrix} = \begin{bmatrix} 16 & 0\\ 0 & 625 \end{bmatrix}$

We can observe that $A^k$ is a diagonal matrix of the same size with the diagonal elements being obtained by raising the corresponding diagonal elements of $A$ to the power of $k$.

In [8]:
import numpy as np

A = np.array([[2,0],[0,5]])

A2 = A @ A
A2

array([[ 4,  0],
       [ 0, 25]])

In [9]:
A3 = A2 @ A
A3

array([[  8,   0],
       [  0, 125]])

In [10]:
A4 = A3 @ A
A4

array([[ 16,   0],
       [  0, 625]])

__Theorem 2 (Properties of matrix product):__

Let $A$ be an $m\times n$ matrix, and let $B$ and $C$ be matrices of the same size for which the following sum and product operations are defined:

1. $A(BC) = (AB)C$


2. $A(B+C) = AB + AC$


3. $(B+C)A = BA + CA$


4. $r(AB) = (rA)B = A(rB)$ for any scalar $r\in \mathbb{R}$.


5. $I_mA = AI_n = A$

Recall that $I_n$ is the $n \times n$ identity matrix.


### Numerical Note

Numpy provides two other methods (built-in functions) to compute the matrix product: `numpy.dot` and `numpy.matmul`. 

They are both used to compute the product of two arrays (e.g., vectors, matrices, and even higher dimensional).

(1). If $A$ and $B$ are vectors (1-D arrays), they both perform dot product of vectors (which we will define in section 6) 

(2).  If $A$ and $B$ are non-vector matrices (2-D arrays), they both perform matrix multiplication, but using `numpy.matmul(A,B)` or `A @ B` is preferred.

(3) For scalar $r\in \mathbb{R}$ `numpy.dot(r,B)` is scalar product `r*B`. But `numpy.malmal(r,B)` and `r @ B` are not defined


__Example 6__

Let A, B, and C be the matrices defined in Example 3. Let's explore the differences between the above operations:

In [136]:
import numpy as np

#A
A = np.array([[1,2,3],[4,5,6]])

#B
B = np.array([[1,2],[3,4],[5,6]])


# for matrices (2D-arrays) of compatible size all methods return matrix product

print('\n A@B = \n', A@B)

print(10*'*')

print('\n np.dot(A,B) = \n', np.dot(A,B))

print(10*'*')

print('\n np.matmul(A,B) = \n', np.matmul(A,B))


 A@B = 
 [[22 28]
 [49 64]]
**********

 np.dot(A,B) = 
 [[22 28]
 [49 64]]
**********

 np.matmul(A,B) = 
 [[22 28]
 [49 64]]


In [11]:
# for vectors (1D arrays) dot and matmul return the dot product
C = [1,2,3]
D = [4,5,6]

print('\n np.dot(C,D) = \n', np.dot(C,D))

print(10*'*')

print('\n np.matmul(C,D) = \n', np.matmul(C,D))


 np.dot(C,D) = 
 32
**********

 np.matmul(C,D) = 
 32


In [14]:
# C@D is not defined for vectors

print('\n A@B = \n', C @ D)

TypeError: unsupported operand type(s) for @: 'list' and 'list'

In [15]:
# If one argument is a real number, dot returns the scalar product
print('\n np.matmul(2,B) = \n', np.dot(A,2)) 


 np.matmul(2,B) = 
 [[ 4  0]
 [ 0 10]]


In [16]:
# If one argument is a real number  @ and matmul are not defined 
2 @ B

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [17]:
np.matmul (2,B)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

### Exercises

```{admonition} Exercises:

1. Which pair of the following matrices can be multiplied? Compute their matrix product.

$A = \begin{bmatrix}
1 & 3 \\
4 & -2 \\
3 & 2
\end{bmatrix}$

$B = \begin{bmatrix}
1 & 4 & 5\\
0 & 2  & 3
\end{bmatrix}$ 


$C = \begin{bmatrix}
1 & 3 & 0\\
2 & -1  & 3 \\
0 & 1 & 1
\end{bmatrix}$ 


2. Find two matrices $A$ and $B$ such that the products $AB$ and $BA$ are defined but $AB \neq BA$.


3.  Given $A= \begin{bmatrix}
1 & 2 \\ 1& 2 \end{bmatrix}$, find a nonzero matrix  $C$ for which $AC= \begin{bmatrix}
0 & 0 \\ 0 & 0
\end{bmatrix}$.
```

## 2.2 Transpose, Inverse and Trace of Matrices

In this section, we will continue studying the basic operators on the set of matrices, focusing on the transpose, inverse, and trace of a square matrix.


** Transpose of a matrix **

Given an $m\times n$ matrix $A$, the transpose of $A$ is the $n\times m$ matrix denoted by $A^T$, whose columns are the corresponding rows of $A$.

__Example 1:__

If $M = \begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}$, then $M^T = \begin{bmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \end{bmatrix}$.

In Python we can either use`narray.T` or `narray.transpose()` to find the transpose of a matrix.

In [2]:
import numpy as np

M = np.array([[1,2],[3, 4],[5,6]])

#Compute the the transpose of M
M_T = M.T

print("M = ", '\n', M, '\n\n', "M_T = ",'\n', M_T)

M =  
 [[1 2]
 [3 4]
 [5 6]] 

 M_T =  
 [[1 3 5]
 [2 4 6]]


In [3]:
#Compute the the transpose of M
M_transpose = M.transpose()

print("M = ", '\n', M, '\n\n', "M_T = ",'\n', M_transpose)

M =  
 [[1 2]
 [3 4]
 [5 6]] 

 M_T =  
 [[1 3 5]
 [2 4 6]]


Note that `transpose` and `T` both have different effect on a list and a list of lists:   

In [4]:
# transpose of a list of lists

np.array([[1,2,3]]).transpose()

array([[1],
       [2],
       [3]])

In [5]:
# does not effect 1D array
np.array([1,2,3]).transpose()

array([1, 2, 3])

### Inverse of a square matrix


An $n\times n$ matrix $A$ is called invertible if there exists an $n\times n$ matrix $B$ such that $AB = BA = I_n$. In this case, $B$ is referred to as the inverse of $A$, denoted as $A^{-1}$. It is important to note that not all matrices are invertible.

__Theorem 3:__

Let $A= \begin{bmatrix} a & b \\ c & d\\ \end{bmatrix}$. If $ad-bc \neq 0$, then $A$ is invertible, and its inverse is given by:

$$
A^{-1}= \frac{1}{ad-bc}\begin{bmatrix} d & -b \\ -c & a\\ \end{bmatrix}
$$

$ad-bc$ is called the __determinant__ of matrix A. The determinant plays a crucial role in determining the invertibility of a square matrix. If the determinant is zero, i.e., $ad-bc = 0$, then matrix A is not invertible. Determinants of matrices will be discussed in the next section, where we will explore their properties and computation methods.

__Example 6:__

1. Find the inverse of $M= \begin{bmatrix} 1 & 2 \\ 3 & 4\\ \end{bmatrix}$.
2. Find the inverse of $N= \begin{bmatrix} 1 & 2 \\ 2 & 4\\ \end{bmatrix}$.

__Solution:__

Let's write a Python code that computes the inverse of a $2\times 2$ matrix:

In [6]:
M = np.array([[1, 2], [3, 4]])
N = np.array([[1, 2], [2, 4]])

# Compute the inverse
def inverse_matrix(matrix):
    a, b = matrix[0]
    c, d = matrix[1]
    
    det = a * d - b * c

    if det == 0:
        print(matrix, "is not invertible")
    else:
        D = 1 / det    
        inverse = np.zeros((2, 2))
        inverse[0, 0] = D * d
        inverse[0, 1] = -D * b
        inverse[1, 0] = -D * c
        inverse[1, 1] = D * a

        return(inverse)

In [7]:
inverse_matrix(M)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [8]:
inverse_matrix(N)

[[1 2]
 [2 4]] is not invertible


__Theorem 3__ (Properties of the inverse matrix)

Let $A$ and $B$ be two invertible $n\times n$ matrices.

1. $(A^{-1})^{-1} = A$
2. $(AB)^{-1} = B^{-1}A^{-1}$
3. $(A^{T})^{-1} = (A^{-1})^{T}$


### Computing the inverse of a matrix

__Theorem 4__

An $n\times n$ matrix $A$ is invertible if and only if it is row equivalent to the identity matrix $I_n$. 


We can use this theorem to find the inverse of a matrix using the row reduction method: set up the augmented matrix $[A|I_n]$ and perform row operations until the left side of the augmented matrix becomes the identity matrix $I_n$. If this is achieved, then the right side of the augmented matrix will be the inverse of $A$. Otherwise, if the left side does not become $I_n$, then the matrix $A$ is not invertible.


__Example 7__ 

Find the inverse of $M= \begin{bmatrix} 0 & 1 & 2\\ 1 & 0 & 3\\ 4 & -3 & 8 \end{bmatrix}$.

__Solution__ Lets set up the augmented matrix and find its RREF:


$$[M|I_3]= \begin{bmatrix} 0 & 1 & 2 && 1 & 0 & 0\\ 1 & 0 & 3 &&  0 & 0 & 1 \\ 4 & -3 & 8 && 0 & 0 & 1\end{bmatrix}$$

In [9]:
# matrix M

M = np.array([[0,1,2], [1,0,3], [4, -3, 8]])
M

array([[ 0,  1,  2],
       [ 1,  0,  3],
       [ 4, -3,  8]])

In [10]:
# identity matrix I_3

I3 = np.eye(3)
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Augmented matrix [A,I_3]

A = np.concatenate((M, I3), axis = 1)
A

array([[ 0.,  1.,  2.,  1.,  0.,  0.],
       [ 1.,  0.,  3.,  0.,  1.,  0.],
       [ 4., -3.,  8.,  0.,  0.,  1.]])

Now lets call row operations

In [12]:
# Elementry row operations:

# Swap two rows

def swap(matrix, row1, row2):
    
    copy_matrix=np.copy(matrix).astype('float64') 
  
    copy_matrix[row1,:] = matrix[row2,:]
    copy_matrix[row2,:] = matrix[row1,:]
    
    return copy_matrix


# Multiple all entries in a row by a nonzero number


def scale(matrix, row, scalar):
    copy_matrix=np.copy(matrix).astype('float64') 
    copy_matrix[row,:] = scalar*matrix[row,:]  
    return copy_matrix

# Replacing a row by the sum of itself and a multiple of another 

def replace(matrix, row1, row2, scalar):
    copy_matrix=np.copy(matrix).astype('float64')
    copy_matrix[row1] = matrix[row1]+ scalar * matrix[row2] 
    return copy_matrix

In [13]:
A_1 = swap(A, 0, 1)
A_1

array([[ 1.,  0.,  3.,  0.,  1.,  0.],
       [ 0.,  1.,  2.,  1.,  0.,  0.],
       [ 4., -3.,  8.,  0.,  0.,  1.]])

In [14]:
A_2 = replace(A_1, 2, 0, -4)
A_2

array([[ 1.,  0.,  3.,  0.,  1.,  0.],
       [ 0.,  1.,  2.,  1.,  0.,  0.],
       [ 0., -3., -4.,  0., -4.,  1.]])

In [15]:
A_3 = replace(A_2, 2, 1, 3)
A_3

array([[ 1.,  0.,  3.,  0.,  1.,  0.],
       [ 0.,  1.,  2.,  1.,  0.,  0.],
       [ 0.,  0.,  2.,  3., -4.,  1.]])

In [16]:
A_4 = scale(A_3, 2, 1/2)
A_4

array([[ 1. ,  0. ,  3. ,  0. ,  1. ,  0. ],
       [ 0. ,  1. ,  2. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  1.5, -2. ,  0.5]])

In [17]:
A_5 = replace(A_4, 1, 2, -2)
A_5

array([[ 1. ,  0. ,  3. ,  0. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  1. ,  1.5, -2. ,  0.5]])

In [18]:
A_6 = replace(A_5, 0, 2, -3)
A_6

array([[ 1. ,  0. ,  0. , -4.5,  7. , -1.5],
       [ 0. ,  1. ,  0. , -2. ,  4. , -1. ],
       [ 0. ,  0. ,  1. ,  1.5, -2. ,  0.5]])

We can see that the resulting matrix is in the form $[I_3, B]$. Thus, $B= \begin{bmatrix} -4.5 & 7 & -1.5\\ -2 &  4 & -1 \\ 1.5 & -2 & 0.5 \\ \end{bmatrix}$ is the inverse of $M$.

__Remark__ We can also use an `np.linalg.inv()` function, from NumPy linear algebra submodule, to find an inverse of a matrix: 

In [19]:
np.linalg.inv(M)

array([[-4.5,  7. , -1.5],
       [-2. ,  4. , -1. ],
       [ 1.5, -2. ,  0.5]])

__Theorem 4__ (The Invertible Matrix Theorem)

Let $A$ be an $n\times n$ matrix. The following statements are equivalent:

1. $A$ is an invertible matrix.
2. $A$ is row equivalent to $I_n$.
3. The equation $A\vec{x}=0$ has only the trivial solution ($\vec{x} = \mathbf{0}$).
4. The columns of $A$ form a linearly independent set.
5. The equation $A\vec{x}=\vec{b}$ has a unique solution ($\vec{x} = A^{-1}\vec{b}$).
6. The columns of $A$ span $\mathbb{R}^n$.

__Example 8__

Find the solution set of the following linear systems:

1. $M\vec{x}=0$, where $M$ is the matrix from Example 7.

__Solution:__ Since $M$ is invertible, by the Invertible Matrix Theorem part (3), the only solution to $M\vec{x}=0$ is the zero vector $\vec{x}=\mathbf{0}$.

2. $M\vec{x}=\vec{b}$, where $M$ is the matrix from Example 7 and $\vec{b}=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$.

__Solution:__ By IMT part (5), the only solution to $M\vec{x}=\vec{b}$ is $\vec{x}=M^{-1}\vec{b}$. In Example 7, we computed the inverse of $M$:

$A^{-1} = \begin{bmatrix} -4.5 & 7 & -1.5 \\ -2 & 4 & -1 \\ 1.5 & -2 & 0.5 \end{bmatrix}$

In the following cell, we use $B$ to represent $A^{-1}$ to simplify notation:

In [21]:
B = np.array([[-4.5, 7, -1.5], [-2, 4, -1], [1.5, -2, 0.5]])

b = np.array ([[1], [2], [3]])

#compute Bb

x = B @ b
x

array([[ 5.],
       [ 3.],
       [-1.]])

In [22]:
M = np.array([[0,1,2], [1,0,3], [4,-3,8]])

#compute Mx

Mx= M @ x
Mx

array([[1.],
       [2.],
       [3.]])

which is $\vec{b}$.

### Trace of Square Matrices

The trace of an $n\times n$ matrix $A$, denoted by $Tr(A)$ or $tr(A)$, is defined as the sum of the elements on its main diagonal:

$$
Tr(A) = a_{11} + a_{22} + \dots + a_{nn} = \sum^{n}_{i=1} a_{ii}
$$

__Theorem 5__ (properties of the trace)

Let $A$ and $B$ be two $n\times n$ matrices, and $c \in \mathbb{R}$. Then we have the following:

1. __Trace of sum:__ $Tr(A + B) = Tr(A) + Tr(B)$

2. __Trace of scalar product:__ $Tr(cA) = c \cdot Tr(A)$

3. __Trace of identity matrix:__ $Tr(I_n) = n$

4. __Trace of product:__ $Tr(AB) = Tr(BA)$

The trace can also be seen as a function from the set of $n\times n$ matrices to real numbers. It can be shown that there is only one function that satisfies the above conditions.

__Example 9__

Let $M = \begin{bmatrix} 0 & 1 & 2\\ 1 & 0 & 3\\ 4 & -3 & 8 \end{bmatrix}$. Then:

$$
Tr(M) = 0 + 0 + 8 = 8.
$$

For large matrices, we can use `numpy.trace()` to compute the trace. The following code generates a random $5\times 5$ matrix and computes its trace:

In [23]:
# generate a 5x5 matrix
A = np.random.rand(5, 5)
print(A)


#compute the trace
Tr_A = np.trace(A)
print('\n Tr(A) = ', Tr_A)

[[0.01885491 0.94056143 0.25729183 0.32348535 0.31284015]
 [0.63032471 0.75771773 0.17459726 0.05278947 0.58316163]
 [0.74847121 0.18847521 0.28978758 0.20410923 0.22665367]
 [0.20345886 0.23354335 0.50383353 0.78272183 0.77366004]
 [0.33258835 0.02049531 0.97957254 0.09030899 0.78366617]]

 Tr(A) =  2.6327482252992613


## Exercises

```{admonition} Exercises
1. Suppose $A= \begin{bmatrix}
1 & 2 \\
0 & -1 \\
3 & 0
\end{bmatrix}$

    (a) Compute $A^T$.
    
    (b) Is $AA^T$ invertible? 
    
    (c) Is $A^TA$ invertible?
    
    

2. The trace is invariant under cyclic permutations, i.e., for three matrices we have $Tr(ABC) = Tr(BCA) = Tr(CAB)$, where $A$ is an $n\times p$ matrix, $B$ is a $p\times m$ matrix, and $C$ is an $m \times n$ matrix. Using Example 9, generate three matrices $A$, $B$, and $C$ such that the product $ABC$ makes sense, and verify that:

$$Tr(ABC) = Tr(BCA) = Tr(CAB)$$
    
```